// Generated by CoffeeScript 1.6.3
var clean, coffee, gulp, spawn;

gulp = require('gulp');

coffee = require('gulp-coffee');

clean = require('gulp-clean');

spawn = require('child_process').spawn;

gulp.task('coffee', function() {
  return gulp.src('index.coffee').pipe(coffee({
    bare: true
  })).pipe(gulp.dest('./'));
});

gulp.task('clean', function() {
  return gulp.src(['index.js', 'coverage'], {
    read: false
  }).pipe(clean());
});

gulp.task('test', ['coffee'], function() {
  return spawn('npm', ['test'], {
    stdio: 'inherit'
  });
});

gulp.task('gulp-reduce', function() {
  var reduce;
  reduce = require('./index.coffee');
  return gulp.src('./{,test/,test/fixtures/}*.coffee').pipe(reduce());
});

gulp.task('default', ['coffee'], function() {
  return gulp.watch(['./{,test/,test/fixtures/}*.coffee'], ['test']);
});
